import Foundation

final class PromptAssembler {
    static let shared = PromptAssembler()

    /// Approximate characters per token for English text.
    private let charsPerToken: Double = 4.0

    private let intentDecomposer = IntentDecomposer.shared
    private let entityExtractor = EntityExtractor.shared
    private let complexityClassifier = ComplexityClassifier.shared
    private let contextEngine = ContextEngineService.shared

    private init() {}

    // MARK: - Public API

    struct AssembledPrompt {
        let systemMessage: String
        let messages: [LLMMessage]
        let estimatedTokenCount: Int
        let wasTruncated: Bool
        let contextBlock: String?
        let contextEntryCount: Int
        let intentAnalysis: IntentAnalysis
        let entityAnalysis: EntityAnalysis
        let complexity: ComplexityResult
        let matchedEntries: [ContextSearchResult]
    }

    /// Assembles a full prompt using the Recursive Meta Prompt Architecture pipeline.
    func assemble(
        rawInput: String,
        style: PromptStyle,
        providerType: LLMProvider,
        verbosity: OutputVerbosity = .concise,
        maxContextTokens: Int = 100_000
    ) async -> AssembledPrompt {
        // STEP 1: Intent decomposition from raw input.
        let intentAnalysis = intentDecomposer.analyze(rawInput)

        // STEP 2: Entity extraction from raw input.
        let entityAnalysis = entityExtractor.analyze(rawInput)

        // STEP 3: Complexity classification from intent, entities, and similarity results.
        let similarityResults = await contextEngine.similarityResults(for: rawInput)
        let complexity = complexityClassifier.classify(
            intentAnalysis: intentAnalysis,
            entityAnalysis: entityAnalysis,
            contextMatches: similarityResults,
            totalContextEntries: contextEngine.entryCount,
            verbosity: verbosity
        )

        // STEP 4: Retrieve context block (top 3 to 5) as XML.
        let contextLimit = complexity.tier == .moderate || complexity.tier == .complex ? 5 : 3
        let contextBlock = contextEngine.buildContextBlock(from: similarityResults, maxEntries: contextLimit)

        // STEP 5: Build system message with placeholders resolved.
        let systemMessage = buildSystemMessage(
            style: style,
            providerType: providerType,
            contextBlock: contextBlock,
            complexityTier: complexity.tier,
            maxOutputWords: complexity.maxOutputWords,
            verbosity: verbosity
        )

        // STEP 6: Construct user message with urgency and tier metadata.
        let userMessage = buildUserMessage(rawInput: rawInput, urgencyLevel: intentAnalysis.urgencyLevel, tier: complexity.tier)

        let systemTokens = estimateTokens(systemMessage)
        let userTokens = estimateTokens(userMessage)
        let reservedOutputTokens = 4096

        let availableForExamples = maxContextTokens - systemTokens - userTokens - reservedOutputTokens
        let tierExamples = selectExamples(
            for: complexity.tier,
            verbosity: verbosity,
            from: style.fewShotExamples
        )
        let (fewShotMessages, wasTruncated) = buildFewShotMessages(
            examples: tierExamples,
            availableTokens: max(0, availableForExamples)
        )

        var allMessages: [LLMMessage] = []
        allMessages.append(contentsOf: fewShotMessages)
        allMessages.append(LLMMessage(role: .user, content: userMessage))

        let totalTokens = systemTokens + fewShotMessages.reduce(0) { $0 + estimateTokens($1.content) } + userTokens

        return AssembledPrompt(
            systemMessage: systemMessage,
            messages: allMessages,
            estimatedTokenCount: totalTokens,
            wasTruncated: wasTruncated,
            contextBlock: contextBlock,
            contextEntryCount: min(contextLimit, similarityResults.count),
            intentAnalysis: intentAnalysis,
            entityAnalysis: entityAnalysis,
            complexity: complexity,
            matchedEntries: similarityResults
        )
    }

    /// Estimates the token count for a given text.
    func estimateTokens(_ text: String) -> Int {
        max(1, Int(ceil(Double(text.count) / charsPerToken)))
    }

    // MARK: - System Message Construction

    private func buildSystemMessage(
        style: PromptStyle,
        providerType: LLMProvider,
        contextBlock: String?,
        complexityTier: ComplexityTier,
        maxOutputWords: Int,
        verbosity: OutputVerbosity
    ) -> String {
        let calibration = buildCalibrationDirective(
            for: complexityTier,
            maxOutputWords: maxOutputWords,
            verbosity: verbosity
        )
        let antiReverse = "Your output must read as if written by a senior engineer, not generated by a prompt optimizer. NEVER include phrases like 'optimized prompt', 'rewritten for clarity', 'the following prompt', or any self-referential language. The output IS the prompt, not a prompt about a prompt."

        var systemTemplate = style.systemInstruction

        // Ensure required placeholders exist for custom styles.
        if !systemTemplate.contains("{{TIER_CALIBRATION}}") {
            systemTemplate = "{{TIER_CALIBRATION}}\n\n" + systemTemplate
        }
        if !systemTemplate.contains("{{LEARNED_CONTEXT}}") {
            systemTemplate += "\n\n{{LEARNED_CONTEXT}}"
        }

        systemTemplate = systemTemplate.replacingOccurrences(of: "{{TIER_CALIBRATION}}", with: calibration)
        systemTemplate = systemTemplate.replacingOccurrences(of: "{{MAX_OUTPUT_WORDS}}", with: "\(maxOutputWords)")
        systemTemplate = systemTemplate.replacingOccurrences(of: "{{LEARNED_CONTEXT}}", with: contextBlock ?? "")

        // Keep provider hint tiny to avoid accidental formatting inflation at low tiers.
        let providerHint: String
        switch providerType {
        case .anthropicClaude, .promptCraftCloud:
            providerHint = "Use XML tags only when tier guidance allows structure."
        case .openAI, .ollama, .custom, .openRouter:
            providerHint = "Use plain prose unless tier guidance explicitly permits structure."
        }

        return "\(systemTemplate)\n\n\(antiReverse)\n\n\(providerHint)"
    }

    // MARK: - Output Calibration

    private func buildCalibrationDirective(
        for tier: ComplexityTier,
        maxOutputWords: Int,
        verbosity: OutputVerbosity
    ) -> String {
        let baseDirective: String
        switch tier {
        case .trivial:
            baseDirective = "ABSOLUTE CONSTRAINT: Your output MUST be 1 to 2 sentences, MAXIMUM \(maxOutputWords) words. ZERO headers, ZERO bullets, ZERO numbered lists, ZERO bold text, ZERO structural formatting of any kind. Write dense, precise prose. If you write a third sentence, STOP and compress. Exceeding this limit means you have FAILED at the core task. This input is simple, respect its simplicity."

        case .simple:
            baseDirective = "CONSTRAINT: Your output MUST be under \(maxOutputWords) words. Maximum 3 numbered items IF the input has 2 distinct sub tasks. NO headers (##). NO bold emphasis. NO 'Output Format' or 'Constraints' sections. Write concise prose or a very short list."

        case .moderate:
            baseDirective = "GUIDANCE: Target \(maxOutputWords) words. You may use headers IF the input has 3 or more genuinely distinct concerns. Each section: 2 to 4 sentences max. Do NOT add sections the user did not request."

        case .complex:
            baseDirective = "GUIDANCE: This is a complex request requiring full structure. Use clear section headers. Target \(maxOutputWords) words. Cover all dimensions the user raised."
        }

        let modeDirective: String
        switch verbosity {
        case .concise:
            modeDirective = "ADDITIONAL CONCISE CONSTRAINT: You are in CONCISE mode. The user explicitly chose brevity. Your output MUST be the absolute minimum words needed to convey the optimized prompt. Strip every adjective that doesn't change meaning. Strip every prepositional phrase that adds context the user already knows. If you can say it in 1 sentence, do NOT use 2. If you can say it in 15 words, do NOT use 30. Think of this as a telegram - every word costs money. The user will judge you harshly for unnecessary words."
        case .balanced:
            modeDirective = "ADDITIONAL BALANCED GUIDANCE: You are in BALANCED mode. Provide moderate detail - more context and specificity than a telegram, but don't over-explain. Include brief rationale or context where it helps the AI receiving this prompt produce better output. A good Balanced output is roughly 1.5-2x the length of the same prompt in Concise mode."
        case .detailed:
            modeDirective = "ADDITIONAL DETAILED GUIDANCE: You are in DETAILED mode. The user explicitly chose maximum detail. Provide comprehensive, structured output regardless of input simplicity. Even for a simple input, add: explicit context, expected output format, constraints, edge cases to handle, and tone guidance. Use headers (##) and bullet points freely. A good Detailed output is 3-5x the length of the same prompt in Concise mode. The user WANTS structure and thoroughness - deliver it."
        }

        return "\(baseDirective)\n\n\(modeDirective)"
    }

    // MARK: - User Message

    private func buildUserMessage(rawInput: String, urgencyLevel: Int, tier: ComplexityTier) -> String {
        "<raw_input urgency=\"\(urgencyLevel)\" tier=\"\(tier.tierNumber)\">\n\(rawInput)\n</raw_input>"
    }

    // MARK: - Few Shot Examples

    private func selectExamples(
        for tier: ComplexityTier,
        verbosity: OutputVerbosity,
        from examples: [FewShotExample]
    ) -> [FewShotExample] {
        let positiveExamples = examples.filter { !$0.isNegative }
        guard !positiveExamples.isEmpty else { return [] }

        let tiered = positiveExamples.filter { $0.tier != nil }
        guard !tiered.isEmpty else { return positiveExamples }

        let allowed: Set<ExampleTier>
        switch verbosity {
        case .concise:
            allowed = [.tier1]
        case .balanced:
            switch tier {
            case .trivial:
                allowed = [.tier1]
            case .simple:
                allowed = [.tier2]
            case .moderate:
                allowed = [.tier3]
            case .complex:
                allowed = [.tier3, .tier4]
            }
        case .detailed:
            allowed = [.tier3, .tier4]
        }

        let filtered = tiered.filter { example in
            guard let tier = example.tier else { return false }
            return allowed.contains(tier)
        }

        return filtered
    }

    /// Builds few shot messages from the style examples, truncating from the end if needed.
    private func buildFewShotMessages(
        examples: [FewShotExample],
        availableTokens: Int
    ) -> (messages: [LLMMessage], wasTruncated: Bool) {
        guard !examples.isEmpty else { return ([], false) }

        var messages: [LLMMessage] = []
        var usedTokens = 0
        var includedCount = 0

        for example in examples {
            let userContent = "<raw_input>\n\(example.input)\n</raw_input>"
            let assistantContent = example.output
            let exampleTokens = estimateTokens(userContent) + estimateTokens(assistantContent)

            if usedTokens + exampleTokens > availableTokens {
                break
            }

            messages.append(LLMMessage(role: .user, content: userContent))
            messages.append(LLMMessage(role: .assistant, content: assistantContent))
            usedTokens += exampleTokens
            includedCount += 1
        }

        let wasTruncated = includedCount < examples.count
        return (messages, wasTruncated)
    }
}
